name: Containerize

on:
  repository_dispatch:
    types: [build_container]

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Git
      run: sudo apt-get install -y git


    - name: Clone go-app repository
      run: |
        git clone https://github.com/coffee-chris94/go-app.git
        cd go-app


    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Install cnspec (cnquery)
      run: |
        bash -c "$(curl -sSL https://install.mondoo.com/sh)"

    - name: Verify Port 8080 is exposed in Dockerfile
      run: |
        # Check if EXPOSE 8080 exists in Dockerfile
        expose_check=$(cnspec run docker file Dockerfile -c "docker.file.instructions" -j | jq '.[0] | .["docker.file.instructions"] | .[] | select(.original | contains("EXPOSE 8080"))')

        if [[ -n "$expose_check" ]]; then
            echo "Port 8080 is exposed in the Dockerfile"
        else
            echo "Port 8080 is NOT exposed in the Dockerfile"
            exit 1
        fi

    - name: Verify Binary Location in Dockerfile
      run: |
        # Check if the binary is copied to the correct location (/app/app)
        binary_check=$(cnspec run docker file Dockerfile -c "docker.file.instructions" -j | jq '.[0] | .["docker.file.instructions"] | .[] | select(.original | contains("COPY --from=builder /app/app ."))')

        if [[ -n "$binary_check" ]]; then
            echo "Binary app is copied to /app/app successfully"
        else
            echo "Binary app was not copied to the correct location"
            exit 1
        fi

    - name: Build and Push Docker Image
      run: |
        # Build the Docker image and push it to DockerHub
        docker build -t cafeespresso/go-web-app:latest .
        docker push cafeespresso/go-web-app:latest
      
